name: Flutter - Android-ios Build Dev

on:
  push:
    branches:
      - android-ios-dev
  pull_request:
    branches:
      - android-ios-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.27.4

      - name: Install Dependencies
        run: flutter pub get

      - name: Install ios dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Auto format the dart code
        run: dart format .

      - name: Verify the dart code is formatted
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze the dart code
        run: flutter analyze --fatal-warnings

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release --build-name=1.0.0 --build-number=1

      - name: Build iOS
        run: flutter build ios --release --build-name=1.0.0 --build-number=1 --no-codesign