name: Flutter - Ios Build Dev

on:
  push:
    branches:
      - ios-dev
  pull_request:
    branches:
      - ios-dev

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.27.4

      - name: Install Dependencies
        run: flutter pub get

      - name: Install ios dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS
        run: flutter build ipa --release --build-name=1.0.0 --build-number=1 --no-codesign
